version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:11-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8f:ac:9f:c6:5e:5f:0e:50:f0:11:cf:97:be:56:66:07"
      - checkout
      - run:
          name: Install
          command: make node_modules
      - run:
          name: Build - public
          command: make public
      - run:
          name: Build - dist
          command: make dist
      - deploy:
          command: make deploy
