version: 2.0
jobs:
  build:
    docker:
      - image: node:12.13.1-buster-slim
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8f:ac:9f:c6:5e:5f:0e:50:f0:11:cf:97:be:56:66:07"
      - checkout
      - run:
          name: Install
          command: make node_modules
      - run:
          name: Build - public
          command: make public
      - run:
          name: Build - dist
          command: make dist
      - run:
          name: Fix host authenticity for 12.34.567.890
          command: |
            ssh-keyscan darrenhurley.co.uk >> ~/.ssh/known_hosts
      - deploy:
          command: make deploy
